listeners:
  - query_port: 25565
    motd: 'Welcome to my Minecraft server!'
    host: 0.0.0.0:25565
    max_players: 100
    bind_local_address: true
    fallback_server: hub
    ping_passthrough: false
    default_server: hub
servers:
  hub:
    address: eaglercraft-docker.railway.internal:25569
    restricted: false
